BTC/EUR:
  max_drawdown_pct: 15
  max_exposure_pct: 30
  risk_per_trade: 0.01
  stop_loss_pct: 5

ETH/EUR:
  max_drawdown_pct: 20
  max_exposure_pct: 40
  risk_per_trade: 0.015
  stop_loss_pct: 6

ADA/EUR:
  max_drawdown_pct: 25
  max_exposure_pct: 50
  risk_per_trade: 0.02
  stop_loss_pct: 7
