name: CI
on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -e .[dev]
      - run: ruff check .
      - run: black --check .
      - run: mypy --strict src/
      - run: pytest -q --maxfail=1 --disable-warnings
