name: CI

on:
  push:
  pull_request:

jobs:
  qa:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Lint (ruff)
        run: |
          ruff version
          ruff check src tests

      - name: Format check (black)
        run: |
          black --version
          black --check src tests

      - name: Type check (mypy --strict)
        run: |
          mypy src tests --strict

      - name: Tests (pytest)
        run: |
          pytest -q
