name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11", cache: "pip" }
      - run: python -m pip install -U pip && pip install -r requirements-dev.txt
      - run: ruff check --output-format=github src tests

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11", cache: "pip" }
      - run: python -m pip install -U pip && pip install -r requirements-dev.txt
      - run: black --check src tests

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11", cache: "pip" }
      - run: python -m pip install -U pip && pip install -r requirements-dev.txt
      - run: mypy src tests --strict --pretty --show-error-codes

  tests:
    runs-on: ubuntu-latest
    needs: [lint, format, typecheck]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11", cache: "pip" }
      - run: python -m pip install -U pip && pip install -r requirements-dev.txt
      - run: pytest -ra --maxfail=1 --durations=10 -q
